language: node_js

node_js:
  - "11"
  - "10"
  - "8"

services:
  - mongodb

before_script:
  - mongo todo-test --eval 'db.createUser({user:"dummy",pwd:"dummy",roles:["readWrite"]});'

notifications:
  email:
    on_success: never
    on_failure: always
