# docker-compose.yaml
version: '3'

services:
  postgresqlserver:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - ./db:/var/lib/postgresql/data
    networks:
      iiifprezi:
        ipv4_address: 10.6.0.6
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgresqlserver
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      iiifprezi:
        ipv4_address: 10.6.0.4
  apiserver:
    build: '.'
    ports:
      - '8080:8080'
    depends_on:
      - postgresqlserver
    environment:
      NODE_ENV: production
      FASTIFY_PORT: 8080
      DB_HOST: postgresqlserver
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: iiif
      API_USERNAME: admin
      API_PASSWORD: admin
    networks:
      iiifprezi:
        ipv4_address: 10.6.0.5
networks:
  iiifprezi:
    driver: bridge
    ipam:
     config:
       - subnet: 10.6.0.0/16
         gateway: 10.6.0.1